<template>
  <div>
    <!-- ========== generated by phpy ========== -->
    <ProjectList v-if="mode === 'LIST'"
                 :projects="projects"
                 @addProject="addProject"
                 @edit="toEdit"
                 @deleteProject="deleteProject"
                 @deleteTask="deleteTask"
    />
    <ProjectForm v-if="mode === 'FORM'"
                 @back="toList"
                 @create="sendPost"
    />
    <!-- <ItemDetail v&#45;if="mode === 'DETAIL'" -->
    <!--              :rec="pickupRec" -->
    <!--              @back="toList" -->
    <!--              @edit="toEdit" -->
    <!--              @delete="deleteRecord" -->
    <!-- /> -->
    <ProjectEditForm v-if="mode === 'EDIT'"
                 :project="pickupRec"
                 @back="toList"
                 @update="sendPut"
    />
    <!-- ========== /generated by phpy ========= -->
  </div>
</template>

<script>
import axios from 'axios'
// ========== generated by phpy ==========
import ProjectList from './ProjectList.vue'
import ProjectForm from './ProjectForm.vue'
import ProjectEditForm from './ProjectEditForm.vue'
// import ItemDetail from './ItemDetail.vue'
// ========== /generated by phpy =========
export default {
  // ========== generated by phpy ==========
  name: 'AppTop',
  components: {
    ProjectForm,
    ProjectList,
    ProjectEditForm,
// ItemDetail
  },
  // ========== /generated by phpy =========
  props: {
    msg: String
  },
  data() {
    return {
      mode: 'LIST',
      projects: JSON.parse(localStorage.getItem('projects')) || [],
      // projects: [],
      pickupRec: null,
      // ========== generated by phpy ==========
      // apiUrl: 'http://localhost:8080/api/item.php'
      apiUrl: 'http://' + location.hostname + ':8080/api/projects'
      // ========== /generated by phpy =========
    }
  },
  mounted() {
    // this.getRecords()
    // for development
    // this.changeDataScm()
    // this._DEV_setId()
  },
  watch: {
    projects: {
      handler: (prj, oldPrj) => {
        console.log(prj)
        console.log(oldPrj)
        console.log('change!')
        localStorage.setItem('projects', JSON.stringify(prj))
      },
      deep: true
    }
  },
  methods: {
    deleteTask(id) {
      console.log('delete')
      console.log(id)
      this.projects.forEach(p => {
        p.tasks = this.deleteTaskRecursive(id, p.tasks)
      })
    },
    deleteTaskRecursive(id, tasks) {
      tasks = tasks.filter(t => t.id !== id)
      tasks.forEach(t => {
        t.sub_tasks = this.deleteTaskRecursive(id, t.sub_tasks)
      })
      return tasks
    },
    addProject() {
      let newProject = {
        "name": "untitled project",
        "done": false,
        "tasks": []
      }
      let newId = localStorage.getItem('max_id_prj')
      newId++;
      newProject.id = newId;
      this.projects.push(newProject)
      localStorage.setItem('max_id_prj', newId)
    },
    deleteProject(id) {
      console.log('delete project')
      console.log(id)
      this.projects = this.projects.filter(p => p.id !== id)
    },
    _DEV_changeDataScm() {
      // for development only!
      this.projects.forEach(p => {
        p.done = false;
        p.tasks.forEach(t => {
          t.done = false;
            t.sub_tasks.forEach(s => {
              s.done = false;
            })
        })
      })
    },
    _DEV_setId() {
      // for development only!
      // IDをレコードに付与するメソッド
      // idの最大値の取得
      let max_id_prj = 0;
      let max_id_tsk = 0;
      this.projects.forEach(p => {
        if (p.id !== undefined && p.id > max_id_prj) {
          max_id_prj = p.id;
        }
        p.tasks.forEach(t => {
          if (t.id !== undefined && t.id > max_id_tsk) {
            max_id_tsk = t.id;
          }
          t.sub_tasks.forEach(s => {
            if (s.id !== undefined && s.id > max_id_tsk) {
              max_id_tsk = s.id;
            }
          })
        })
      })
      console.log(max_id_prj);
      console.log(max_id_tsk);
      localStorage.setItem('max_id_prj', max_id_prj)
      localStorage.setItem('max_id_tsk', max_id_tsk)
      // idが空の要素にidを付与
      this.projects.forEach(p => {
        if (p.id === undefined) {
          p.id = max_id_prj;
          max_id_prj++;
        }
        p.tasks.forEach(t => {
          if (t.id === undefined) {
            t.id = max_id_tsk;
            max_id_tsk++;
          }
          t.sub_tasks.forEach(s => {
            if (s.id === undefined) {
              s.id = max_id_tsk;
              max_id_tsk++;
            }
          })
        })
      })
      console.log(max_id_prj);
      console.log(max_id_tsk);
      localStorage.setItem('projects', JSON.stringify(this.projects))
      localStorage.setItem('max_id_prj', max_id_prj)
      localStorage.setItem('max_id_tsk', max_id_tsk)


    },
    getRecords() {
      axios.get(this.apiUrl).then(res => {
        console.log(res);
        this.projects = res.data;
      });
    },
    sendPost(rec) {
      console.log(rec);
      axios.post(this.apiUrl, rec).then(res => {
        console.log('send!')
        console.log(res)  // temporary
        this.mode = 'LIST'
        this.getRecords()
      })
    },
    sendPut(rec) {
      console.log('put!')
      console.log(rec);
      axios.put(this.apiUrl + '/' + rec.id, rec).then(res => {
        console.log('send!')
        console.log(res)  // temporary
        this.mode = 'LIST'
        this.getRecords()
      })
    },
    deleteRecord(recId) {
      console.log(recId);
      axios.delete(this.apiUrl + '/' + recId, {data: recId}).then(res => {
        console.log('delete!')
        console.log(res)  // temporary
        this.mode = 'LIST'
        this.getRecords()
      })
    },
    toCreate() {
      console.log('create')
      this.mode = 'FORM'
    },
    // toDetail(recId) {
    //   console.log(recId)
    //   axios.get(this.apiUrl, {params: {id: recId}}).then(res => {
    //     console.log(res);
    //     this.pickupRec = res.data[0]
    //     // this.records = res.data;
    //     this.mode = 'DETAIL'
    //   });
    // },
    toEdit(recId) {
      this.pickupRec = this.projects.filter(p => p.id == recId)[0]
      this.mode = 'EDIT'
    },
    toList() {
      this.mode = 'LIST'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
