<template>
  <div class="hello">
    <!-- ========== generated by phpy ========== -->
    <h2>Item form</h2>
    <!-- ========== /generated by phpy ========= -->
    <div class="card-panel">
      <!-- ========== generated by phpy ========== -->
      <div class="row">
        <div class="input-field col s12">
          <input v-model="item_name" id="item_name" type="text">
          <label for="item_name">item_name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input v-model="price" id="price" type="text">
          <label for="price">price</label>
        </div>
      </div>
      <!-- ========== /generated by phpy ========= -->
    </div>
    <a @click="back" class="waves-effect waves-light btn grey">戻る</a>
    &nbsp;
    <a @click="send" class="waves-effect waves-light btn">登録</a>
  </div>
</template>

<script>
// import axios from 'axios'
export default {
  // ========== generated by phpy ==========
  name: 'ItemForm',
  // ========== /generated by phpy =========
  props: {
    msg: String
  },
  data() {
    return {
        // ========== generated by phpy ==========
        item_name: '',
        price: '',
        // ========== /generated by phpy =========
    }
  },
  methods: {
    back() {
      this.$emit('back')
    },
    send() {
      this.$emit('create', {
        // ========== generated by phpy ==========
        item_name: this.item_name,
        price: this.price,
        // ========== /generated by phpy =========
      })
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
