<template>
  <div>
    <!-- ========== generated by phpy ========== -->
    <h2>Item form</h2>
    <!-- ========== /generated by phpy ========= -->
    <div class="card-panel">
      <table class="highlight">
        <tbody>
          <!-- ========== generated by phpy ========== -->
            <tr>
              <td>item_name</td>
              <td>{{rec.item_name}}</td>
            </tr>
            <tr>
              <td>price</td>
              <td>{{rec.price}}</td>
            </tr>
          <!-- ========== /generated by phpy ========= -->
        </tbody>
      </table>
    </div>
    <a @click="back" class="waves-effect waves-light btn grey">戻る</a>
    &nbsp;
    <a @click="edit" class="waves-effect waves-light btn">編集</a>
    &nbsp;&nbsp;
    <a @click="del" class="waves-effect waves-light btn red">削除</a>
  </div>
</template>

<script>
// import axios from 'axios'
export default {
  // ========== generated by phpy ==========
  name: 'ItemDetail',
  // ========== /generated by phpy =========
  props: {
    rec: Object
  },
  methods: {
    back() {
      this.$emit('back')
    },
    edit() {
      this.$emit('edit')
    },
    del() {
      this.$emit('delete', this.rec)
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
