<template>
  <div class="hello">
    <!-- ========== generated by phpy ========== -->
    <h2>Item form</h2>
    <!-- ========== /generated by phpy ========= -->
    <div class="card-panel">
      <!-- ========== generated by phpy ========== -->
      <div class="row">
        <div class="input-field col s12">
          <input v-model="project.name" id="project_name" type="text">
          <label for="project_name">project_name</label>
        </div>
      </div>
      <!-- ========== /generated by phpy ========= -->
    </div>
    <a @click="back" class="waves-effect waves-light btn grey">戻る</a>
    &nbsp;
    <a @click="send" class="waves-effect waves-light btn">登録</a>
  </div>
</template>

<script>
// import axios from 'axios'
export default {
  // ========== generated by phpy ==========
  name: 'ItemEditForm',
  // ========== /generated by phpy =========
  props: {
    project: Object
  },
  methods: {
    back() {
      this.$emit('back')
    },
    send() {
      this.$emit('update', this.project)
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
